name: Makefile CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup
      run: make setup

    - name: test
      run: make test

    - name: lint
      run: make lint

